# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pattern' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pattern
  pod 'RxSwift', '~> 5.0'

  target 'PatternTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '~> 5.0'
  end

  target 'PatternUITests' do
    # Pods for testing
    pod 'RxSwift', '~> 5.0'
  end

end
